root = "."
tmp_dir = "temp"

[build]
#  bin = "./main serve"
#  cmd = "go build -o ./main ."
  delay = 1000
  exclude_dir = ["storage", "database",".git",".idea","web","web\\node_modules","dist"]
  exclude_file = []
  exclude_regex = ["web","node_modules"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
  bin = "./main.exe serve"
  cmd = "go build -o ./main.exe ."

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
