app:
  name: "OrangBus.cn"
  url: http://localhost:3000
  debug: false
  key: admin666
  port: 3002
db:
  driver: sqlite
  host: home.cc
  port: 3306
  database: sqlite.db
  user: root
  password: admin666

proxy:
  url: https://spider.orangbus.cn?url=